const POSTS = [
    {
        id: 1, category: 'Gaming, Entertainment, Film', title: 'EA has reportedly cancelled its story-driven Star Wars game', content: 'Now, according to Kotaku’s Jason Schreier, EA has officially cancelled the game, despite the studio responsible, EA Vancouver, having largely restarted from scratch with what it inherited from Visceral back in October 2017. EA was not immediately available for comment.The news is a sad end for a project that many fans hoped would carry the flame for narrative Star Wars games.he franchise has historically been home to some of the most formative role-playing titles in the industry, when LucasArts'
    },
    {
        id: 2, category: 'Tech, YouTube, Culture', title: 'YouTube’s guidelines now address dangerous pranks following Bird Box, Tide Pod challenges', content: 'YouTube is home to many beloved viral challenges and pranks, but we need to make sure what’s funny doesn’t cross the line into also being harmful or dangerous. We’ve made it clear that our policies prohibiting harmful and dangerous content also extend to pranks with a perceived danger of serious physical injury. We don’t allow pranks that make victims believe they’re in serious physical danger — for example, a home invasion prank or a drive-by shooting prank.'
    },
    {
        id: 3, category: 'Web, Tech, Twitter', title: 'Twitter brings the reverse-chronological feed to Android', content: 'Twitter brought its traditional reverse-chronological timeline back to iOS last month, and now the optional feature is available to Android users in a new update. It’s a welcome choice that brings back some stability to the Twitter feed. Twitter switched to an algorithm-based timeline four years ago during a time when social networks like Facebook and Instagram were experimenting with how best to display feeds to users.'
    },
    {
        id: 4, category: 'Microsoft, Gaming, Policy & Law', title: 'Forza Horizon 4 removes dance emotes at the center of ongoing Fortnite copyright lawsuits', content: 'Microsoft-owned Turn 10 Studios, which develops the Forza series of racing games for Xbox and PC, today announced it would be removing two controversial dance emotes from its latest entry, Forza Horizon 4. The news, spotted by Polygon and announced on Forza’s website as part of the most recent update release notes, marks the first instance of a game developer backing away from asserting its right to copy and include a virtual version of a dance move popularized in real life. The news follows numerous lawsuits against Fortnite creator Epic Games for doing the same in its massively popular battle royale game.'
    },
    {
        id: 5, category: 'Science', title: 'CERN wants to build the biggest, baddest particle collider ever', content: 'The design for the Future Collision Collider lays out a few different potential aspects of the facility. There’s the huge tunnel, which will let the thin beams of particles travel without having to navigate curves that are quite as tight (relatively) as the LHC’s. Then there’s a collider called a lepton collider which would, well, smash particles called leptons together. It could potentially give researchers more accurate measurements of the Higgs and other particles that scientists are just starting to understand. There’s also another larger hadron collider that would be able to smash particles together at even higher energies.'
    },
    {
        id: 6, category: 'Apple, Policy & Law, US & World', title: 'Tim Cook calls on FTC to let consumers track and delete their personal data', content: 'Apple CEO Tim Cook has called on the US government to introduce new tools to help users control the online data collected about their lives. Writing in an op-ed for Time magazine, Cook said consumers should have the power to delete their data on demand, freely, easily and online, once and for all.As head of a company that makes privacy a key selling point, Cook has long extolled the virtues of minimal data-collection. But in recent years, as scandals involving big tech companies like Facebook and smaller data brokers like Equifax, have brought shady practices into the light, his message has become more strident. It’s moved from abstract discussions of the rights and wrongs of data collection to concrete calls for legislation.'
    },
    {
        id: 7, category: 'Gaming, Nintendo, Culture', title: 'Nintendo’s Switch Online is slowly turning into an amazing classic games service', content: 'Nintendo is terrible when it comes to the internet, and in a lot of ways, the Switch Online subscription service is no different. There are annoying restrictions around cloud saves, for instance, and voice chat is relegated to a mobile app. It can feel archaic, especially compared to Xbox Live or PlayStation Plus. But there’s one aspect of the service that has become an indispensable part of how I use my Switch: the free retro games.The best part of Switch Online is the included NES app, which gets you access to a handful of 8-bit classics as part of the price of your subscription. It’s sort of like Netflix for NES games, and while it started out with a fairly slim selection, it now features an increasingly robust library.'
    },
    {
        id: 8, category: 'Google, Policy & Law, US & World', title: 'This is what Google says search will look like under EU copyright laws', content: 'Last September, the European Parliament voted in favor of the Copyright Directive: a sweeping piece of legislation intended to update copyright for the internet age, but critics said it would fundamentally break the internet. Now, as negotiations over the directive’s final wording draw to a close, Google has issued a warning about the damage the directive might do in an unusual format: an empty search results page.To be more precise, it’s an empty search results page for news. One of the most controversial segments of the Copyright Directive is Article 11, which gives publishers the right to demand paid licenses for using snippets of their stories. From Google’s point of view, that gives it two choices: start paying for licenses or don’t show snippets at all.'
    },
    {
        id: 9, category: 'Transportation, Cars, Audi', title: 'Four top Audi employees indicted in Dieselgate scandal', content: 'A federal grand jury in Detroit has indicted four former Audi managers for their alleged role in the German automaker’s scheme to cheat US emissions testing on diesel-powered cars, according to a new court document published Thursday. Audi’s malfeasance was part of a larger effort from parent company Volkswagen Group to sell millions of cars with engines that were dirtier than regulations allowed, a scandal that was uncovered in 2015 and has since been dubbed Dieselgate.Ripple effects were still showing up, even before Thursday’s indictments. Audi’s CEO was forced out in October after he was arrested by German authorities. The European Union’s antitrust regulators are also investigating whether Volkswagen, BMW, and Daimler (the parent company of Mercedes-Benz) colluded to slow the rollout of better emissions technology. And Winterkorn has been indicted in the US on charges similar to the ones announced Thursday, though he remains in Germany.'
    },
    {
        id: 10, category: 'Entertainment, Netflix, Culture', title: 'Netflix shares huge numbers for original content as Disney’s streaming service nears', content: 'Netflix has released numbers for some of its films and series — a show of strength to investors ahead of upcoming streaming wars with Disney and AT&T.Bird Box, which Netflix previously reported accrued more than 45 million unique account streams seven days after its release, has now surpassed 80 million views, according to CEO Reed Hastings’ letter to investors. You, a Lifetime series that Netflix has purchased the rights to, will surpass 40 million household streams within the first four weeks of its release. The same goes for new Netflix original series, Sex Education. Hastings’ letter states that Netflix accounts for 10 percent of all television viewing in the United States.It’s an impressive feat, and one that Hastings really wants to hammer home for investors as the streaming wars gear up. Disney is planning to launch its standalone streaming service, Disney+, this fall; WarnerMedia’s streaming service will also launch later this year; NBCUniversal and Comcast are working on their own service, and that doesn’t even account for streaming platforms like CBS All Access and Hulu — the latter of which has seen spectacular growth over the last year. Hastings isn’t worried.'
    }

];
export default POSTS;